export const mock = [
  {
    name: "Fútbol Cancha",
    city: "Buenos Aires",
    price: "10000",
    image: "https://images2.alphacoders.com/121/1214052.png",
    sports: "Fútbol",
  },
  {
    name: "F5 Canchas",
    city: "Buenos Aires",
    price: "15000",
    image: "https://images2.alphacoders.com/121/1214052.png",
    sports: "Fútbol",
  },
  {
    name: "Canchitas F5",
    city: "Buenos Aires",
    price: "12000",
    image: "https://images2.alphacoders.com/121/1214052.png",
    sports: "Fútbol",
  },
  {
    name: "Buenos Aires Fútbol",
    city: "Buenos Aires",
    price: "11000",
    image: "https://images2.alphacoders.com/121/1214052.png",
    sports: "Fútbol",
  },
  {
    name: "Complejo Básquet",
    city: "Buenos Aires",
    price: "13000",
    image: "https://images2.alphacoders.com/121/1214052.png",
    sports: "Básquet",
  },
  {
    name: "Fútbol por Hora",
    city: "Buenos Aires",
    price: "10000",
    image: "https://images2.alphacoders.com/121/1214052.png",
    sports: "Fútbol",
  },
  {
    name: "Cancha 2",
    city: "Buenos Aires",
    price: "11500",
    image: "https://images2.alphacoders.com/121/1214052.png",
    sports: "Fútbol",
  },
  {
    name: "Canchas Vóley",
    city: "Buenos Aires",
    price: "12000",
    image: "https://images2.alphacoders.com/121/1214052.png",
    sports: "Vóley",
  },
  {
    name: "Fútbol Camp",
    city: "Buenos Aires",
    price: "9000",
    image: "https://images2.alphacoders.com/121/1214052.png",
    sports: "Fútbol",
  },
  {
    name: "Cancha San Martín",
    city: "Buenos Aires",
    price: "18000",
    image: "https://images2.alphacoders.com/121/1214052.png",
    sports: "Padel",
  },
  {
    name: "Belgrano Fútbol",
    city: "Buenos Aires",
    price: "19000",
    image: "https://images2.alphacoders.com/121/1214052.png",
    sports: "Fútbol",
  },
  {
    name: "Saavedra Básquet",
    city: "Buenos Aires",
    price: "11000",
    image: "https://images2.alphacoders.com/121/1214052.png",
    sports: "Básquet",
  },
  {
    name: "Mendoza Padel",
    city: "Buenos Aires",
    price: "14000",
    image: "https://images2.alphacoders.com/121/1214052.png",
    sports: "Padel",
  },
  {
    name: "San Cristóbal",
    city: "Buenos Aires",
    price: "8000",
    image: "https://images2.alphacoders.com/121/1214052.png",
    sports: "Tenis",
  },
  {
    name: "Dorrego Fútbol",
    city: "Buenos Aires",
    price: "9000",
    image: "https://images2.alphacoders.com/121/1214052.png",
    sports: "Fútbol",
  },
  {
    name: "San Martín",
    city: "Rosario",
    price: "7000",
    image: "https://images2.alphacoders.com/121/1214052.png",
    sports: "Tenis",
  },
  {
    name: "Quique Fútbol",
    city: "Rosario",
    price: "6000",
    image: "https://images2.alphacoders.com/121/1214052.png",
    sports: "Fútbol",
  },
  {
    name: "Romario Futebol",
    city: "Rosario",
    price: "17400",
    image: "https://images2.alphacoders.com/121/1214052.png",
    sports: "Fútbol",
  },
  {
    name: "Chapu Canchas",
    city: "Rosario",
    price: "14030",
    image: "https://images2.alphacoders.com/121/1214052.png",
    sports: "Vóley",
  },
  {
    name: "Blanco Encalada Básquet",
    city: "Rosario",
    price: "4500",
    image: "https://images2.alphacoders.com/121/1214052.png",
    sports: "Básquet",
  },
  {
    name: "San Lorenzo de Rosario",
    city: "Rosario",
    price: "13000",
    image: "https://images2.alphacoders.com/121/1214052.png",
    sports: "Básquet",
  },
  {
    name: "Constitución",
    city: "Rosario",
    price: "10000",
    image: "https://images2.alphacoders.com/121/1214052.png",
    sports: "Vóley",
  },
  {
    name: "Messi F5",
    city: "Rosario",
    price: "10000",
    image: "https://images2.alphacoders.com/121/1214052.png",
    sports: "Fútbol",
  },
  {
    name: "Di María F5",
    city: "Rosario",
    price: "11000",
    image: "https://images2.alphacoders.com/121/1214052.png",
    sports: "Fútbol",
  },
  {
    name: "Vóley Rosario",
    city: "Rosario",
    price: "9000",
    image: "https://images2.alphacoders.com/121/1214052.png",
    sports: "Vóley",
  },
  {
    name: "Rosario Sur",
    city: "Rosario",
    price: "6000",
    image: "https://images2.alphacoders.com/121/1214052.png",
    sports: "Padel",
  },
  {
    name: "Rosario Norte",
    city: "Rosario",
    price: "12000",
    image: "https://images2.alphacoders.com/121/1214052.png",
    sports: "Tenis",
  },
  {
    name: "F5 Ahora",
    city: "Rosario",
    price: "10000",
    image: "https://images2.alphacoders.com/121/1214052.png",
    sports: "Fútbol",
  },
  {
    name: "Talleres de Córdoba",
    city: "Córdoba",
    price: "15000",
    image: "https://images2.alphacoders.com/121/1214052.png",
    sports: "Fútbol",
  },
  {
    name: "Guemes Padel",
    city: "Córdoba",
    price: "8000",
    image: "https://images2.alphacoders.com/121/1214052.png",
    sports: "Padel",
  },
  {
    name: "San Girona",
    city: "Córdoba",
    price: "13000",
    image: "https://images2.alphacoders.com/121/1214052.png",
    sports: "Padel",
  },
  {
    name: "Solís Fútbol",
    city: "Córdoba",
    price: "12000",
    image: "https://images2.alphacoders.com/121/1214052.png",
    sports: "Fútbol",
  },
  {
    name: "Pueyrredón Básquet",
    city: "Córdoba",
    price: "13000",
    image: "https://images2.alphacoders.com/121/1214052.png",
    sports: "Básquet",
  },
  {
    name: "Chacabuco Fútbol",
    city: "Córdoba",
    price: "14000",
    image: "https://images2.alphacoders.com/121/1214052.png",
    sports: "Fútbol",
  },
  {
    name: "Federico Lacroze",
    city: "Córdoba",
    price: "9000",
    image: "https://images2.alphacoders.com/121/1214052.png",
    sports: "Tenis",
  },
  {
    name: "Sol de Mayo",
    city: "Córdoba",
    price: "16000",
    image: "https://images2.alphacoders.com/121/1214052.png",
    sports: "Básquet",
  },
  {
    name: "Club Parque",
    city: "Córdoba",
    price: "11000",
    image: "https://images2.alphacoders.com/121/1214052.png",
    sports: "Vóley",
  },
  {
    name: "Cullen Padel",
    city: "Córdoba",
    price: "9000",
    image: "https://images2.alphacoders.com/121/1214052.png",
    sports: "Padel",
  },
  {
    name: "Crespo Fútbol",
    city: "Córdoba",
    price: "4300",
    image: "https://images2.alphacoders.com/121/1214052.png",
    sports: "Fútbol",
  },
  {
    name: "Lo de Pepe Fútbol",
    city: "Córdoba",
    price: "8000",
    image: "https://images2.alphacoders.com/121/1214052.png",
    sports: "Fútbol",
  },
  {
    name: "Cancha 3",
    city: "Córdoba",
    price: "11600",
    image: "https://images2.alphacoders.com/121/1214052.png",
    sports: "Tenis",
  },
  {
    name: "Vóley Pueyrredón",
    city: "Córdoba",
    price: "6000",
    image: "https://images2.alphacoders.com/121/1214052.png",
    sports: "Vóley",
  },
  {
    name: "Silvera Fútbol",
    city: "Córdoba",
    price: "4600",
    image: "https://images2.alphacoders.com/121/1214052.png",
    sports: "Fútbol",
  },
];
