const mock = [
  {
    name: "Canchas Vóley",
    image:
      "https://i.pinimg.com/550x/00/d4/ea/00d4eaf5da36ee2f3fb79de64292ebd5.jpg",
    service: "",
    address: "Av José Ignacio de la Roza Oeste 1946",
    city: "Buenos Aires",
    phone: "",
    paymentMethod: "",
    shift: "",
    pice: 9000,
    Sports: [{ name: "Vóley" }],
    status: true,
  },
  {
    name: "Fútbol Camp",
    image:
      "https://media.tycsports.com/files/2020/06/29/105088/futbol-5_416x234.jpg?v=2",
    status: true,
    service: "",
    address: "Arenales 3648",
    city: "Buenos Aires",
    phone: "",
    paymentMethod: "",
    shift: "",
    price: 9000,
    Sports: [{ name: "Fútbol" }],
    status: true,
  },
  {
    name: "Cancha San Martín",
    image:
      "https://i.pinimg.com/550x/00/d4/ea/00d4eaf5da36ee2f3fb79de64292ebd5.jpg",
    service: "",
    address: "Av Santa Fe 3253",
    city: "Buenos Aires",
    phone: "",
    paymentMethod: "",
    shift: "",
    price: 18000,
    Sports: [{ name: "Padel" }],
    status: true,
  },
  {
    name: "Belgrano Fútbol",
    image:
      "https://www.neuqueninforma.gob.ar/wp-content/uploads/2022/10/web-Cancha-de-cesped-sintetico-El-Alamito-46.jpg",
    service: "",
    address: "Av Belgrano Norte 388",
    city: "Buenos Aires",
    phone: "",
    paymentMethod: "",
    shift: "",
    price: 19000,
    Sports: [{ name: "Fútbol" }],
    status: true,
  },
  {
    name: "Saavedra Básquet",
    image:
      "https://media.tycsports.com/files/2020/06/29/105088/futbol-5_416x234.jpg?v=2",
    status: true,
    service: "",
    address: "Buenos Aires 353",
    city: "Buenos Aires",
    phone: "",
    paymentMethod: "",
    shift: "",
    price: 11000,
    Sports: [{ name: "Básquet" }],
    status: true,
  },
  {
    name: "Mendoza Padel",
    image:
      "https://www.neuqueninforma.gob.ar/wp-content/uploads/2022/10/web-Cancha-de-cesped-sintetico-El-Alamito-46.jpg",
    service: "",
    address: "Av Rioja Norte 304",
    city: "Buenos Aires",
    phone: "",
    paymentMethod: "",
    shift: "",
    price: 14000,
    Sports: [{ name: "Padel" }, { name: "Básquet" }],
    status: true,
  },
  {
    name: "San Cristóbal",
    image:
      "https://i.pinimg.com/550x/00/d4/ea/00d4eaf5da36ee2f3fb79de64292ebd5.jpg",
    service: "",
    address: "De la Ermita 3462",
    city: "Buenos Aires",
    phone: "",
    paymentMethod: "",
    shift: "",
    price: 8000,
    Sports: [{ name: "Tenis" }, { name: "Vóley" }],
    status: true,
  },
  {
    name: "Dorrego Fútbol",
    image:
      "https://media.tycsports.com/files/2020/06/29/105088/futbol-5_416x234.jpg?v=2",
    status: true,
    service: "",
    address: "Paysandú 99",
    city: "Buenos Aires",
    phone: "",
    paymentMethod: "",
    shift: "",
    price: 9000,
    Sports: [{ name: "Fútbol" }],
    status: true,
  },
  {
    name: "San Martín",
    image:
      "https://www.neuqueninforma.gob.ar/wp-content/uploads/2022/10/web-Cancha-de-cesped-sintetico-El-Alamito-46.jpg",
    service: "",
    address: "Alvarado 950",
    city: "Rosario",
    phone: "",
    paymentMethod: "",
    shift: "",
    price: 7000,
    Sports: [{ name: "Tenis" }, { name: "Vóley" }],
    status: true,
  },
  {
    name: "Quique Fútbol",
    image:
      "https://i.pinimg.com/550x/00/d4/ea/00d4eaf5da36ee2f3fb79de64292ebd5.jpg",
    service: "",
    address: "Pres. Roberto M. Ortiz 1871",
    city: "Rosario",
    phone: "",
    paymentMethod: "",
    shift: "",
    price: 6000,
    Sports: [{ name: "Fútbol" }],
    status: true,
  },
  {
    name: "Buenos Aires Fútbol",
    image:
      "https://i.pinimg.com/550x/00/d4/ea/00d4eaf5da36ee2f3fb79de64292ebd5.jpg",
    service: "",
    address: "General Güemes 118",
    city: "Buenos Aires",
    phone: "",
    paymentMethod: "",
    shift: "",
    price: 11000,
    Sports: [{ name: "Fútbol" }],
    status: true,
  },
  {
    name: "Complejo Básquet",
    image:
      "https://i.pinimg.com/550x/00/d4/ea/00d4eaf5da36ee2f3fb79de64292ebd5.jpg",
    service: "",
    address: "La Rioja 455",
    city: "Buenos Aires",
    phone: "",
    paymentMethod: "",
    shift: "",
    price: 13000,
    Sports: [{ name: "Básquet" }],
    status: true,
  },
  {
    name: "Fútbol Cancha",
    image:
      "https://www.neuqueninforma.gob.ar/wp-content/uploads/2022/10/web-Cancha-de-cesped-sintetico-El-Alamito-46.jpg",
    service: "",
    address: "Santa Rosa 826",
    city: "Buenos Aires",
    phone: "",
    paymentMethod: "",
    shift: "",
    price: 10000,
    Sports: [{ name: "Fútbol" }, { name: "Padel" }],
    status: true,
  },
  {
    name: "F5 Canchas",
    image:
      "https://i.pinimg.com/550x/00/d4/ea/00d4eaf5da36ee2f3fb79de64292ebd5.jpg",
    service: "",
    address: "Av Santa Fe 4000",
    city: "Buenos Aires",
    phone: "",
    paymentMethod: "",
    shift: "",
    price: 15000,
    Sports: [{ name: "Fútbol" }],
    status: true,
  },
  {
    name: "Canchitas F5",
    image:
      "https://media.tycsports.com/files/2020/06/29/105088/futbol-5_416x234.jpg?v=2",
    status: true,
    service: "",
    address: "25 de Mayo 147",
    city: "Buenos Aires",
    phone: "",
    paymentMethod: "",
    shift: "",
    price: 12000,
    Sports: [{ name: "Fútbol" }],
    status: true,
  },
  {
    name: "Fútbol por Hora",
    image:
      "https://media.tycsports.com/files/2020/06/29/105088/futbol-5_416x234.jpg?v=2",
    status: true,
    service: "",
    address: "Mariano Fragueiro 2020",
    city: "Buenos Aires",
    phone: "",
    paymentMethod: "",
    shift: "",
    price: 10000,
    Sports: [{ name: "Fútbol" }],
    status: true,
  },
  {
    name: "Cancha 2",
    image:
      "https://www.neuqueninforma.gob.ar/wp-content/uploads/2022/10/web-Cancha-de-cesped-sintetico-El-Alamito-46.jpg",
    service: "",
    address: "Av Zanon Eguia",
    city: "Buenos Aires",
    phone: "",
    paymentMethod: "",
    shift: "",
    price: 11500,
    Sports: [{ name: "Fútbol" }, { name: "Padel" }],
    status: true,
  },
  {
    name: "Romario Futebol",
    image:
      "https://media.tycsports.com/files/2020/06/29/105088/futbol-5_416x234.jpg?v=2",
    status: true,
    service: "",
    address: "Av Belgrano (S) 979",
    city: "Rosario",
    phone: "",
    paymentMethod: "",
    shift: "",
    price: 17400,
    Sports: [{ name: "Fútbol" }],
    status: true,
  },
  {
    name: "Chapu Canchas",
    image:
      "https://i.pinimg.com/550x/00/d4/ea/00d4eaf5da36ee2f3fb79de64292ebd5.jpg",
    service: "",
    address: "Av General Las Heras 558",
    city: "Rosario",
    phone: "",
    paymentMethod: "",
    shift: "",
    price: 14030,
    Sports: [{ name: "Vóley" }],
    status: true,
  },
  {
    name: "Blanco Encalada Básquet",
    image:
      "https://www.neuqueninforma.gob.ar/wp-content/uploads/2022/10/web-Cancha-de-cesped-sintetico-El-Alamito-46.jpg",
    service: "",
    address: "Av 24 de Septiembre 893",
    city: "Rosario",
    phone: "",
    paymentMethod: "",
    shift: "",
    price: 4500,
    Sports: [{ name: "Básquet" }, { name: "Vóley" }],
    status: true,
  },
  {
    name: "San Lorenzo de Rosario",
    image:
      "https://media.tycsports.com/files/2020/06/29/105088/futbol-5_416x234.jpg?v=2",
    status: true,
    service: "",
    address: "Av Entre Ríos 2139",
    city: "Rosario",
    phone: "",
    paymentMethod: "",
    shift: "",
    price: 13000,
    Sports: [{ name: "Básquet" }, { name: "Vóley" }],
    status: true,
  },
  {
    name: "Constitución",
    image:
      "https://www.neuqueninforma.gob.ar/wp-content/uploads/2022/10/web-Cancha-de-cesped-sintetico-El-Alamito-46.jpg",
    service: "",
    address: "Maitén 7869",
    city: "Rosario",
    phone: "",
    paymentMethod: "",
    shift: "",
    price: 10000,
    Sports: [{ name: "Vóley" }, { name: "Padel" }],
    status: true,
  },
  {
    name: "Messi F5",
    image:
      "https://media.tycsports.com/files/2020/06/29/105088/futbol-5_416x234.jpg?v=2",
    status: true,
    service: "",
    address: "	Av Pres. Figueroa Alcorta 6402",
    city: "Rosario",
    phone: "",
    paymentMethod: "",
    shift: "",
    price: 10000,
    Sports: [{ name: "Fútbol" }],
    status: true,
  },
  {
    name: "Di María F5",
    image:
      "https://i.pinimg.com/550x/00/d4/ea/00d4eaf5da36ee2f3fb79de64292ebd5.jpg",
    service: "",
    address: "Av Rafael Núñez 4684",
    city: "Rosario",
    phone: "",
    paymentMethod: "",
    shift: "",
    price: 11000,
    Sports: [{ name: "Fútbol" }],
    status: true,
  },
  {
    name: "Vóley Rosario",
    image:
      "https://media.tycsports.com/files/2020/06/29/105088/futbol-5_416x234.jpg?v=2",
    status: true,
    service: "",
    address: "9 de Julio",
    city: "Rosario",
    phone: "",
    paymentMethod: "",
    shift: "",
    price: 9000,
    Sports: [{ name: "Vóley" }],
    status: true,
  },
  {
    name: "Rosario Sur",
    image:
      "https://i.pinimg.com/550x/00/d4/ea/00d4eaf5da36ee2f3fb79de64292ebd5.jpg",
    service: "",
    address: "Dique I Puerto Santa Fe",
    city: "Rosario",
    phone: "",
    paymentMethod: "",
    shift: "",
    price: 6000,
    Sports: [{ name: "Padel" }, { name: "Vóley" }],
    status: true,
  },
  {
    name: "Rosario Norte",
    image:
      "https://media.tycsports.com/files/2020/06/29/105088/futbol-5_416x234.jpg?v=2",
    status: true,
    service: "",
    address: "Av Concepción Arenal",
    city: "Rosario",
    phone: "",
    paymentMethod: "",
    shift: "",
    pice: 8900,
    Sports: [{ name: "Tenis" }, { name: "Básquet" }],
    status: true,
  },
  {
    name: "F5 Ahora",
    image:
      "https://i.pinimg.com/550x/00/d4/ea/00d4eaf5da36ee2f3fb79de64292ebd5.jpg",
    service: "",
    address: "Av Duarte Quirós 69",
    city: "Rosario",
    phone: "",
    paymentMethod: "",
    shift: "",
    price: 10000,
    Sports: [{ name: "Fútbol" }],
    status: true,
  },
  {
    name: "Talleres de Córdoba",
    image:
      "https://www.neuqueninforma.gob.ar/wp-content/uploads/2022/10/web-Cancha-de-cesped-sintetico-El-Alamito-46.jpg",
    service: "",
    address: "Av San Pedrito 1450",
    city: "Córdoba",
    phone: "",
    paymentMethod: "",
    shift: "",
    pice: 9200,
    Sports: [{ name: "Fútbol" }, { name: "Básquet" }],
    status: true,
  },
  {
    name: "Guemes Padel",
    image:
      "https://i.pinimg.com/550x/00/d4/ea/00d4eaf5da36ee2f3fb79de64292ebd5.jpg",
    service: "",
    address: "Honduras 4141",
    city: "Córdoba",
    phone: "",
    paymentMethod: "",
    shift: "",
    price: 8000,
    Sports: [{ name: "Padel" }],
    status: true,
  },
  {
    name: "San Girona",
    image:
      "https://www.neuqueninforma.gob.ar/wp-content/uploads/2022/10/web-Cancha-de-cesped-sintetico-El-Alamito-46.jpg",
    service: "",
    address: "Avenida Hipólito Yrigoyen 81",
    city: "Córdoba",
    phone: "",
    paymentMethod: "",
    shift: "",
    price: 13000,
    Sports: [{ name: "Padel" }, { name: "Básquet" }],
    status: true,
  },
  {
    name: "Solís Fútbol",
    image:
      "https://media.tycsports.com/files/2020/06/29/105088/futbol-5_416x234.jpg?v=2",
    status: true,
    service: "",
    address: "Félix San Martín 890",
    city: "Córdoba",
    phone: "",
    paymentMethod: "",
    shift: "",
    pice: 11100,
    Sports: [{ name: "Fútbol" }],
    status: true,
  },
  {
    name: "Pueyrredón Básquet",
    image:
      "https://i.pinimg.com/550x/00/d4/ea/00d4eaf5da36ee2f3fb79de64292ebd5.jpg",
    service: "",
    address: "Juan Julián Lastra 2400",
    city: "Córdoba",
    phone: "",
    paymentMethod: "",
    shift: "",
    price: 13000,
    Sports: [{ name: "Básquet" }],
    status: true,
  },
  {
    name: "Chacabuco Fútbol",
    image:
      "https://i.pinimg.com/550x/00/d4/ea/00d4eaf5da36ee2f3fb79de64292ebd5.jpg",
    service: "",
    address: "Obispo Salguero 495",
    city: "Córdoba",
    phone: "",
    paymentMethod: "",
    shift: "",
    price: 14000,
    Sports: [{ name: "Fútbol" }, { name: "Básquet" }],
    status: true,
  },
  {
    name: "Federico Lacroze",
    image:
      "https://www.neuqueninforma.gob.ar/wp-content/uploads/2022/10/web-Cancha-de-cesped-sintetico-El-Alamito-46.jpg",
    service: "",
    address: "Juncal 1230",
    city: "Córdoba",
    phone: "",
    paymentMethod: "",
    shift: "",
    price: 9000,
    Sports: [{ name: "Tenis" }, { name: "Fútbol" }],
    status: true,
  },
  {
    name: "Sol de Mayo",
    image:
      "https://media.tycsports.com/files/2020/06/29/105088/futbol-5_416x234.jpg?v=2",
    status: true,
    service: "",
    address: "Av Del Libertador 2047",
    city: "Córdoba",
    phone: "",
    paymentMethod: "",
    shift: "",
    price: 16000,
    Sports: [{ name: "Básquet" }, { name: "Fútbol" }, { name: "Tenis" }],
    status: true,
  },
  {
    name: "Club Parque",
    image:
      "https://i.pinimg.com/550x/00/d4/ea/00d4eaf5da36ee2f3fb79de64292ebd5.jpg",
    service: "",
    address: "Av Rafael Núñez 5019",
    city: "Córdoba",
    phone: "",
    paymentMethod: "",
    shift: "",
    price: 11000,
    Sports: [{ name: "Vóley" }, { name: "Fútbol" }, { name: "Tenis" }],
    status: true,
  },
  {
    name: "Cullen Padel",
    image:
      "https://www.neuqueninforma.gob.ar/wp-content/uploads/2022/10/web-Cancha-de-cesped-sintetico-El-Alamito-46.jpg",
    service: "",
    address: "José Aaron Salmún Feijóo 928",
    city: "Córdoba",
    phone: "",
    paymentMethod: "",
    shift: "",
    price: 9000,
    Sports: [{ name: "Padel" }, { name: "Fútbol" }],
    status: true,
  },
  {
    name: "Crespo Fútbol",
    image:
      "https://i.pinimg.com/550x/00/d4/ea/00d4eaf5da36ee2f3fb79de64292ebd5.jpg",
    service: "",
    address: "Yerbal 2461",
    city: "Córdoba",
    phone: "",
    paymentMethod: "",
    shift: "",
    price: 4300,
    Sports: [{ name: "Fútbol" }],
    status: true,
  },
  {
    name: "Lo de Pepe Fútbol",
    image:
      "https://media.tycsports.com/files/2020/06/29/105088/futbol-5_416x234.jpg?v=2",
    status: true,
    service: "",
    address: "Av Segurola 1949",
    city: "Córdoba",
    phone: "",
    paymentMethod: "",
    shift: "",
    price: 8000,
    Sports: [{ name: "Fútbol" }],
    status: true,
  },
  {
    name: "Cancha 3",
    image:
      "https://www.neuqueninforma.gob.ar/wp-content/uploads/2022/10/web-Cancha-de-cesped-sintetico-El-Alamito-46.jpg",
    service: "",
    address: "25 de Mayo 2740",
    city: "Córdoba",
    phone: "",
    paymentMethod: "",
    shift: "",
    price: 11600,
    Sports: [{ name: "Tenis" }, { name: "Fútbol" }],
    status: true,
  },
  {
    name: "Vóley Pueyrredón",
    image:
      "https://i.pinimg.com/550x/00/d4/ea/00d4eaf5da36ee2f3fb79de64292ebd5.jpg",
    service: "",
    address: "Av Luis María Campos 1174",
    city: "Córdoba",
    phone: "",
    paymentMethod: "",
    shift: "",
    price: 6000,
    Sports: [{ name: "Vóley" }],
    status: true,
  },
  {
    name: "Silvera Fútbol",
    image:
      "https://media.tycsports.com/files/2020/06/29/105088/futbol-5_416x234.jpg?v=2",
    status: true,
    service: "",
    address: "Av Corrientes 1343",
    city: "Córdoba",
    phone: "",
    paymentMethod: "",
    shift: "",
    price: 4600,
    Sports: [{ name: "Fútbol" }],
    status: true,
  },
];

module.exports = mock;
